# Generated by Django 5.2.5 on 2025-08-12 13:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hrac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cenik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('SOLO', 'Solo (1 hráč)'), ('DVOJICE', 'Dvojice (2 hráči)'), ('TROJICE', 'Trojice (3 hráči)'), ('CTVRICE', 'Čtveřice (4 hráči)')], max_length=8)),
                ('kurt', models.CharField(choices=[('VENEK', 'Venek'), ('HALA', 'Hala')], max_length=8)),
                ('cena_za_hodinu', models.DecimalField(decimal_places=2, max_digits=8)),
                ('platnost_od', models.DateField(default=django.utils.timezone.now)),
                ('platnost_do', models.DateField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['format', 'kurt', 'platnost_od', 'platnost_do'], name='core_cenik_format_7d5e8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transakce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('NAUCTOVANO', 'Naúčtováno'), ('PLATBA', 'Platba'), ('VRATKA', 'Vrácení/bonifikace'), ('UPRAVA', 'Úprava')], max_length=12)),
                ('castka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('popis', models.CharField(blank=True, max_length=240)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('hrac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transakce', to='core.hrac')),
            ],
            options={
                'ordering': ['-vytvoreno'],
            },
        ),
        migrations.CreateModel(
            name='Dochazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prisel', models.BooleanField(default=True)),
                ('castka_nauc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nauceno_kdy', models.DateTimeField(blank=True, null=True)),
                ('hrac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dochazky', to='core.hrac')),
                ('transakce_nauc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zdroj_dochazky', to='core.transakce')),
            ],
        ),
        migrations.CreateModel(
            name='Trening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField()),
                ('delka_minut', models.PositiveIntegerField(default=60)),
                ('format', models.CharField(choices=[('SOLO', 'Solo (1 hráč)'), ('DVOJICE', 'Dvojice (2 hráči)'), ('TROJICE', 'Trojice (3 hráči)'), ('CTVRICE', 'Čtveřice (4 hráči)')], max_length=8)),
                ('kurt', models.CharField(choices=[('VENEK', 'Venek'), ('HALA', 'Hala')], max_length=8)),
                ('poznamka', models.CharField(blank=True, max_length=240)),
                ('hraci', models.ManyToManyField(related_name='treningy', through='core.Dochazka', to='core.hrac')),
                ('trener', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transakce',
            name='trening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trening'),
        ),
        migrations.AddField(
            model_name='dochazka',
            name='trening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dochazky', to='core.trening'),
        ),
        migrations.AlterUniqueTogether(
            name='dochazka',
            unique_together={('trening', 'hrac')},
        ),
    ]
