# Generated by Django 5.2.5 on 2025-08-12 16:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrac',
            name='pocet_treninku_od_vyuctovani',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hrac',
            name='posledni_vyuctovani_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hrac',
            name='vyuctovani_n',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='hrac',
            name='vyuctovani_rezim',
            field=models.CharField(choices=[('MESICNE', 'Měsíčně'), ('N_TRENINGU', 'Po N trénincích'), ('CASTKA', 'Po dosažení částky')], default='MESICNE', max_length=16),
        ),
        migrations.AddField(
            model_name='hrac',
            name='vyuctovani_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='Vyuctovani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.DateTimeField(blank=True, null=True)),
                ('period_to', models.DateTimeField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sessions_count', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(default='manual', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hrac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vyuctovani', to='core.hrac')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
