# Generated by Django 5.2.5 on 2025-08-13 12:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hrac_pocet_treninku_od_vyuctovani_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cenik',
            options={'verbose_name': 'Ceník', 'verbose_name_plural': 'Ceník'},
        ),
        migrations.AlterModelOptions(
            name='hrac',
            options={'verbose_name': 'Hráč', 'verbose_name_plural': 'Hráči'},
        ),
        migrations.AlterModelOptions(
            name='transakce',
            options={'ordering': ['-vytvoreno'], 'verbose_name': 'Platba', 'verbose_name_plural': 'Platby'},
        ),
        migrations.AlterModelOptions(
            name='trening',
            options={'verbose_name': 'Trénink', 'verbose_name_plural': 'Tréninky'},
        ),
        migrations.AlterModelOptions(
            name='vyuctovani',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vyúčtování', 'verbose_name_plural': 'Vyúčtování'},
        ),
        migrations.AddField(
            model_name='vyuctovani',
            name='charges_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='vyuctovani',
            name='credit_end',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='vyuctovani',
            name='credit_start',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='vyuctovani',
            name='payments_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='cenik',
            name='format',
            field=models.CharField(choices=[('SOLO', 'Solo (1 hráč)'), ('DVOJICE', 'Dvojice (2 hráči)'), ('TROJICE', 'Trojice (3 hráči)'), ('CTVRICE', 'Čtveřice (4 hráči)'), ('PETICE', 'Pětice (5 a více hráčů)')], max_length=8),
        ),
        migrations.AlterField(
            model_name='cenik',
            name='kurt',
            field=models.CharField(choices=[('VENEK', 'Venku'), ('HALA', 'Hala')], max_length=8),
        ),
        migrations.AlterField(
            model_name='trening',
            name='format',
            field=models.CharField(choices=[('SOLO', 'Solo (1 hráč)'), ('DVOJICE', 'Dvojice (2 hráči)'), ('TROJICE', 'Trojice (3 hráči)'), ('CTVRICE', 'Čtveřice (4 hráči)'), ('PETICE', 'Pětice (5 a více hráčů)')], max_length=8),
        ),
        migrations.AlterField(
            model_name='trening',
            name='kurt',
            field=models.CharField(choices=[('VENEK', 'Venku'), ('HALA', 'Hala')], max_length=8),
        ),
    ]
