# Generated by Django 5.2.5 on 2025-08-20 18:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cenik_options_alter_hrac_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrenerProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sazba_za_hodinu', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trener_profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trenér – sazba',
                'verbose_name_plural': 'Trenéři – sazby',
            },
        ),
    ]
