# Generated by Django 5.2.5 on 2025-08-20 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trenerprofil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrenerSazba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platnost_od', models.DateField()),
                ('platnost_do', models.DateField(blank=True, null=True)),
                ('sazba_za_hodinu', models.DecimalField(decimal_places=2, max_digits=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trenerske_sazby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trenér – sazba (období)',
                'verbose_name_plural': 'Trenéři – sazby (období)',
                'ordering': ('-platnost_od',),
                'indexes': [models.Index(fields=['user', 'platnost_od', 'platnost_do'], name='core_trener_user_id_da1e38_idx')],
            },
        ),
    ]
