# Generated by Django 5.2.5 on 2025-08-20 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trenersazba'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrenerPlatba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poznamka', models.CharField(blank=True, max_length=240)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platby_trenerovi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Výplata trenérovi',
                'verbose_name_plural': 'Výplaty trenérům',
                'ordering': ['-vytvoreno'],
            },
        ),
    ]
