# Generated by Django 5.2.5 on 2025-08-23 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trenerplatba'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trenerplatba',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trener_platby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trenerplatba',
            index=models.Index(fields=['user', 'vytvoreno'], name='core_trener_user_id_ed903f_idx'),
        ),
    ]
