# Generated by Django 5.2.5 on 2025-08-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_trenerplatba_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrac',
            options={'ordering': ('prijmeni', 'jmeno'), 'verbose_name': 'Hráč', 'verbose_name_plural': 'Hráči'},
        ),
        migrations.AddField(
            model_name='hrac',
            name='prijmeni',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='hrac',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='hrac',
            name='jmeno',
            field=models.CharField(max_length=120, verbose_name='Jméno'),
        ),
        migrations.AddIndex(
            model_name='hrac',
            index=models.Index(fields=['prijmeni', 'jmeno'], name='core_hrac_prijmen_5561bb_idx'),
        ),
    ]
