# Generated by Django 5.2.5 on 2025-08-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_hrac_options_hrac_prijmeni_alter_hrac_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrac',
            options={'ordering': ('jmeno',), 'verbose_name': 'Hráč', 'verbose_name_plural': 'Hráči'},
        ),
        migrations.RemoveIndex(
            model_name='hrac',
            name='core_hrac_prijmen_5561bb_idx',
        ),
        migrations.RemoveField(
            model_name='hrac',
            name='prijmeni',
        ),
        migrations.AlterField(
            model_name='hrac',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hrac',
            name='jmeno',
            field=models.CharField(max_length=120),
        ),
    ]
