# Generated by Django 5.2.5 on 2025-08-30 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_hrac_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.PositiveIntegerField(unique=True, verbose_name='Číslo rodiny')),
                ('nazev', models.CharField(blank=True, default='', max_length=120, verbose_name='Název rodiny (např. Peterkovi)')),
                ('kontakt_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('kontakt_telefon', models.CharField(blank=True, default='', max_length=40)),
                ('poznamka', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Rodina',
                'verbose_name_plural': 'Rodiny',
                'ordering': ('cislo',),
            },
        ),
        migrations.AddField(
            model_name='hrac',
            name='rodina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clenove', to='core.rodina'),
        ),
    ]
