# Generated by Django 5.2.5 on 2025-08-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rodina_hrac_rodina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rodina',
            options={'ordering': ('nazev', 'id'), 'verbose_name': 'Rodina', 'verbose_name_plural': 'Rodiny'},
        ),
        migrations.RemoveField(
            model_name='rodina',
            name='cislo',
        ),
    ]
