# Generated by Django 5.2.5 on 2025-10-24 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_rodina_options_remove_rodina_cislo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transakce',
            name='trening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trening'),
        ),
    ]
