# Generated by Django 5.2.5 on 2025-10-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_transakce_trening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cenik',
            name='format',
            field=models.CharField(choices=[('SOLO_C', 'Solo (1 hráč) - Člen'), ('DVOJICE_C', 'Dvojice (2 hráči) - Člen'), ('TROJICE_C', 'Trojice (3 hráči) - Člen'), ('CTVRICE_C', 'Čtveřice (4 hráči) - Člen'), ('PETICE', 'Pětice (5 a více hráčů)'), ('SOLO_NC', 'Solo Nečlen (1 hráč)'), ('DVOJICE_NC', 'Dvojice Nečlen (2 hráči)'), ('TROJICE_NC', 'Trojice Nečlen (3 hráči)'), ('CTVRICE_NC', 'Čtveřice Nečlen (4 hráči)'), ('V_STAND', 'Výplet (400 Kč) - Standard'), ('V_EXCEL', 'Výplet excel (530 Kč)'), ('V_VLAST', 'Výplet vlastní (250 Kč)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cenik',
            name='kurt',
            field=models.CharField(choices=[('VENEK', 'Venku'), ('HALA', 'Hala'), ('SLUZBA', 'Služba (neplatí pro kurt)')], max_length=8),
        ),
        migrations.AlterField(
            model_name='trening',
            name='format',
            field=models.CharField(choices=[('SOLO_C', 'Solo (1 hráč) - Člen'), ('DVOJICE_C', 'Dvojice (2 hráči) - Člen'), ('TROJICE_C', 'Trojice (3 hráči) - Člen'), ('CTVRICE_C', 'Čtveřice (4 hráči) - Člen'), ('PETICE', 'Pětice (5 a více hráčů)'), ('SOLO_NC', 'Solo Nečlen (1 hráč)'), ('DVOJICE_NC', 'Dvojice Nečlen (2 hráči)'), ('TROJICE_NC', 'Trojice Nečlen (3 hráči)'), ('CTVRICE_NC', 'Čtveřice Nečlen (4 hráči)'), ('V_STAND', 'Výplet (400 Kč) - Standard'), ('V_EXCEL', 'Výplet excel (530 Kč)'), ('V_VLAST', 'Výplet vlastní (250 Kč)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trening',
            name='kurt',
            field=models.CharField(choices=[('VENEK', 'Venku'), ('HALA', 'Hala'), ('SLUZBA', 'Služba (neplatí pro kurt)')], max_length=8),
        ),
    ]
