# Generated by Django 5.2.5 on 2025-10-24 23:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_cenik_format_alter_cenik_kurt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transakce',
            name='vytvoreno',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum platby'),
        ),
        migrations.AlterField(
            model_name='trenerplatba',
            name='vytvoreno',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum výplaty'),
        ),
    ]
