# Generated by Django 5.2.5 on 2026-03-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_trening_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dochazka',
            options={'verbose_name_plural': 'Hráči'},
        ),
    ]
