# Generated by Django 5.2.5 on 2026-07-11 13:29

from decimal import Decimal
from django.db import migrations, models


def seed_vyuctovani_nastaveni(apps, schema_editor):
    Model = apps.get_model("core", "VyuctovaniNastaveni")
    Model.objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_dochazka_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VyuctovaniNastaveni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_limit', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Po naúčtování tréninku se vyúčtování vytvoří, když dluh hráče od poslední uzávěrky dosáhne této částky.', max_digits=10, verbose_name='Limit dluhu pro automatické vyúčtování (Kč)')),
                ('auto_posilat_email', models.BooleanField(default=True, verbose_name='Posílat e-mail při automatickém vyúčtování')),
                ('email_variant', models.CharField(choices=[('1', 'Účet 1 AJ Sport'), ('2', 'Účet 2 Káťa')], default='1', max_length=1, verbose_name='Výchozí varianta e-mailu')),
                ('ucet_varianta_1', models.CharField(default='2102303853/2700', max_length=32, verbose_name='Číslo účtu – varianta 1')),
                ('ucet_varianta_2', models.CharField(default='2108539314/2700', max_length=32, verbose_name='Číslo účtu – varianta 2')),
                ('vychozi_rezim', models.CharField(choices=[('MESICNE', 'Měsíčně'), ('N_TRENINGU', 'Po N trénincích'), ('CASTKA', 'Po dosažení částky')], default='MESICNE', max_length=16, verbose_name='Výchozí režim pro nové hráče')),
                ('vychozi_pocet_treninku', models.PositiveIntegerField(default=10, verbose_name='Výchozí počet tréninků (režim Po N trénincích)')),
                ('vychozi_castka_prah', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10, verbose_name='Výchozí práh částky (režim Po dosažení částky)')),
                ('mesicni_aktivni', models.BooleanField(default=False, help_text='Připravuje se – zatím lze vyúčtovat ručně nebo automaticky podle dluhu.', verbose_name='Měsíční vyúčtování (plánované)')),
                ('mesicni_den', models.PositiveSmallIntegerField(default=1, verbose_name='Den v měsíci pro měsíční vyúčtování')),
            ],
            options={
                'verbose_name': 'Nastavení vyúčtování',
                'verbose_name_plural': 'Nastavení vyúčtování',
            },
        ),
        migrations.RunPython(seed_vyuctovani_nastaveni, migrations.RunPython.noop),
    ]
