# Generated by Django 5.2.5 on 2026-07-11 13:52

from decimal import Decimal
from django.db import migrations, models


def migrate_nastaveni_rezim(apps, schema_editor):
    Model = apps.get_model("core", "VyuctovaniNastaveni")
    for row in Model.objects.filter(pk=1):
        if hasattr(row, "vychozi_rezim") and row.vychozi_rezim:
            row.auto_rezim = row.vychozi_rezim
            row.save(update_fields=["auto_rezim"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_vyuctovani_nastaveni"),
    ]

    operations = [
        migrations.AddField(
            model_name="vyuctovaninastaveni",
            name="auto_rezim",
            field=models.CharField(
                choices=[
                    ("CASTKA", "Limit dluhu"),
                    ("MESICNE", "Měsíčně"),
                    ("N_TRENINGU", "Dle odehraných tréninků"),
                ],
                default="CASTKA",
                max_length=16,
                verbose_name="Způsob automatického vyúčtování",
            ),
        ),
        migrations.RenameField(
            model_name="vyuctovaninastaveni",
            old_name="vychozi_pocet_treninku",
            new_name="auto_pocet_treninku",
        ),
        migrations.RunPython(migrate_nastaveni_rezim, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="vyuctovaninastaveni",
            name="mesicni_aktivni",
        ),
        migrations.RemoveField(
            model_name="vyuctovaninastaveni",
            name="vychozi_castka_prah",
        ),
        migrations.RemoveField(
            model_name="vyuctovaninastaveni",
            name="vychozi_rezim",
        ),
        migrations.AlterField(
            model_name="vyuctovaninastaveni",
            name="auto_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5000.00"),
                help_text="Vyúčtování se vytvoří, když dluh hráče od poslední uzávěrky dosáhne této částky.",
                max_digits=10,
                verbose_name="Limit dluhu (Kč)",
            ),
        ),
        migrations.AlterField(
            model_name="vyuctovaninastaveni",
            name="auto_pocet_treninku",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Po tolika odehraných trénincích od poslední uzávěrky se vyúčtuje.",
                verbose_name="Počet tréninků",
            ),
        ),
        migrations.AlterField(
            model_name="vyuctovaninastaveni",
            name="mesicni_den",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Od tohoto dne v měsíci (po dalším tréninku) proběhne měsíční uzávěrka.",
                verbose_name="Den v měsíci",
            ),
        ),
    ]
