# Generated by Django 5.2.5 on 2026-07-11 13:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_vyuctovani_auto_rezim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cenik',
            name='format',
            field=models.CharField(choices=[('SOLO_C', 'Solo (1 hráč) - Člen'), ('DVOJICE_C', 'Dvojice (2 hráči) - Člen'), ('TROJICE_C', 'Trojice (3 hráči) - Člen'), ('CTVRICE_C', 'Čtveřice (4 hráči) - Člen'), ('PETICE', 'Pětice (5 a více hráčů) - Člen'), ('SOLO_NC', 'Solo (1 hráč) - Nečlen'), ('DVOJICE_NC', 'Dvojice (2 hráči) - Nečlen'), ('TROJICE_NC', 'Trojice (3 hráči) - Nečlen'), ('CTVRICE_NC', 'Čtveřice (4 hráči) - Nečlen'), ('SOBOTA_TRE', 'Trénink - Sobota'), ('KURT_TRE', 'Kurt - Rezervace'), ('V_STAND', 'Výplet - Standard'), ('V_EXCEL', 'Výplet - Express'), ('V_VLAST', 'Výplet - Vlastní')], max_length=15),
        ),
        migrations.AlterField(
            model_name='hrac',
            name='vyuctovani_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='trening',
            name='format',
            field=models.CharField(choices=[('SOLO_C', 'Solo (1 hráč) - Člen'), ('DVOJICE_C', 'Dvojice (2 hráči) - Člen'), ('TROJICE_C', 'Trojice (3 hráči) - Člen'), ('CTVRICE_C', 'Čtveřice (4 hráči) - Člen'), ('PETICE', 'Pětice (5 a více hráčů) - Člen'), ('SOLO_NC', 'Solo (1 hráč) - Nečlen'), ('DVOJICE_NC', 'Dvojice (2 hráči) - Nečlen'), ('TROJICE_NC', 'Trojice (3 hráči) - Nečlen'), ('CTVRICE_NC', 'Čtveřice (4 hráči) - Nečlen'), ('SOBOTA_TRE', 'Trénink - Sobota'), ('KURT_TRE', 'Kurt - Rezervace'), ('V_STAND', 'Výplet - Standard'), ('V_EXCEL', 'Výplet - Express'), ('V_VLAST', 'Výplet - Vlastní')], max_length=15),
        ),
        migrations.AlterField(
            model_name='vyuctovani',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='K úhradě'),
        ),
        migrations.AlterField(
            model_name='vyuctovani',
            name='charges_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Naúčtováno'),
        ),
        migrations.AlterField(
            model_name='vyuctovani',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='vyuctovani',
            name='credit_end',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Kredit na konci'),
        ),
        migrations.AlterField(
            model_name='vyuctovani',
            name='credit_start',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Kredit na začátku'),
        ),
        migrations.AlterField(
            model_name='vyuctovani',
            name='hrac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vyuctovani', to='core.hrac', verbose_name='Hráč'),
        ),
        migrations.AlterField(
            model_name='vyuctovani',
            name='payments_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Platby a vratky'),
        ),
        migrations.AlterField(
            model_name='vyuctovani',
            name='period_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Období od'),
        ),
        migrations.AlterField(
            model_name='vyuctovani',
            name='period_to',
            field=models.DateTimeField(verbose_name='Období do'),
        ),
        migrations.AlterField(
            model_name='vyuctovani',
            name='reason',
            field=models.CharField(default='manual', max_length=32, verbose_name='Důvod'),
        ),
        migrations.AlterField(
            model_name='vyuctovani',
            name='sessions_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Počet tréninků'),
        ),
    ]
