# Generated by Django 5.2.5 on 2026-07-11 14:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_cenik_format_alter_hrac_vyuctovani_threshold_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrac",
            name="vyuctovani_rezim",
            field=models.CharField(
                choices=[
                    ("MESICNE", "Měsíčně"),
                    ("N_TRENINGU", "Po N trénincích"),
                    ("CASTKA", "Limit kreditu"),
                ],
                default="MESICNE",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="vyuctovaninastaveni",
            name="auto_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5000.00"),
                help_text="Vyúčtování se vytvoří, když kredit hráče klesne na tuto zápornou částku nebo níže (např. −5000 Kč).",
                max_digits=10,
                verbose_name="Limit kreditu (Kč)",
            ),
        ),
        migrations.AlterField(
            model_name="vyuctovaninastaveni",
            name="auto_rezim",
            field=models.CharField(
                choices=[
                    ("CASTKA", "Limit kreditu"),
                    ("MESICNE", "Měsíčně"),
                    ("N_TRENINGU", "Dle odehraných tréninků"),
                ],
                default="CASTKA",
                max_length=16,
                verbose_name="Způsob automatického vyúčtování",
            ),
        ),
    ]
