# Generated by Django 5.2.5 on 2026-07-11 14:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_kredit_limit_vyuctovani"),
    ]

    operations = [
        migrations.AddField(
            model_name="vyuctovaninastaveni",
            name="auto_castka_k_uhrade",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5000.00"),
                help_text="Částka zobrazená v e-mailu jako požadavek k úhradě. Ponechte 0 pro automatický výpočet z období.",
                max_digits=10,
                verbose_name="Částka k zaplacení v e-mailu (Kč)",
            ),
        ),
    ]
