# Generated by Django 5.2.5 on 2026-07-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_vyuctovani_castka_k_uhrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="vyuctovani",
            name="snapshot_transakce_pk",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Interní ukotvení pro detekci opakovaného vyúčtování.",
                verbose_name="Poslední transakce v uzávěrce",
            ),
        ),
    ]
