# Generated by Django 5.2.5 on 2026-07-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_vyuctovani_snapshot_transakce_pk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vyuctovaninastaveni",
            name="auto_rezim",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Pouze manuálně"),
                    ("CASTKA", "Limit kreditu"),
                    ("MESICNE", "Měsíčně"),
                    ("N_TRENINGU", "Dle odehraných tréninků"),
                ],
                default="CASTKA",
                max_length=16,
                verbose_name="Způsob vyúčtování",
            ),
        ),
    ]
