# Generated by Django 5.2.5 on 2026-07-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_vyuctovani_manual_rezim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vyuctovaninastaveni',
            name='auto_rezim',
            field=models.CharField(choices=[('CASTKA', 'Limit kreditu'), ('MESICNE', 'Měsíčně'), ('N_TRENINGU', 'Dle odehraných tréninků'), ('MANUAL', 'Pouze manuálně')], default='CASTKA', max_length=16, verbose_name='Způsob vyúčtování'),
        ),
    ]
