# Generated by Django 5.2.5 on 2026-07-11 21:30

from django.db import migrations, models


VYCHOZI_KODY = {
    "Solo (1 hráč) - Člen": ("SOLO_C", 10),
    "Dvojice (2 hráči) - Člen": ("DVOJICE_C", 20),
    "Trojice (3 hráči) - Člen": ("TROJICE_C", 30),
    "Čtveřice (4 hráči) - Člen": ("CTVRICE_C", 40),
    "Pětice (5 a více hráčů) - Člen": ("PETICE", 50),
    "Solo (1 hráč) - Nečlen": ("SOLO_NC", 60),
    "Dvojice (2 hráči) - Nečlen": ("DVOJICE_NC", 70),
    "Trojice (3 hráči) - Nečlen": ("TROJICE_NC", 80),
    "Čtveřice (4 hráči) - Nečlen": ("CTVRICE_NC", 90),
    "Trénink - Sobota": ("SOBOTA_TRE", 100),
    "Kurt - Rezervace": ("KURT_TRE", 110),
    "Výplet - Standard": ("V_STAND", 120),
    "Výplet - Express": ("V_EXCEL", 130),
    "Výplet - Vlastní": ("V_VLAST", 140),
}

KOD_TO_NAZEV = {kod: nazev for nazev, (kod, _poradi) in VYCHOZI_KODY.items()}


def seed_formats(apps, schema_editor):
    CenikFormat = apps.get_model("core", "CenikFormat")
    Cenik = apps.get_model("core", "Cenik")
    Trening = apps.get_model("core", "Trening")

    seen_kody = set()
    for nazev, (kod, poradi) in VYCHOZI_KODY.items():
        fmt = CenikFormat.objects.filter(nazev=nazev).first()
        if fmt is None:
            fmt = CenikFormat.objects.filter(kod=kod).first()
        if fmt is None:
            CenikFormat.objects.create(kod=kod, nazev=nazev, poradi=poradi)
        else:
            changed = False
            if fmt.kod != kod:
                fmt.kod = kod
                changed = True
            if fmt.nazev != nazev:
                fmt.nazev = nazev
                changed = True
            if fmt.poradi != poradi:
                fmt.poradi = poradi
                changed = True
            if changed:
                fmt.save()
        seen_kody.add(kod)

    extra_poradi = 200
    for model in (Cenik, Trening):
        for kod in model.objects.values_list("format", flat=True).distinct():
            if not kod or kod in seen_kody:
                continue
            nazev = KOD_TO_NAZEV.get(kod, kod)
            fmt = CenikFormat.objects.filter(kod=kod).first()
            if fmt is None:
                fmt = CenikFormat.objects.filter(nazev=nazev).first()
            if fmt is None:
                CenikFormat.objects.create(kod=kod, nazev=nazev, poradi=extra_poradi)
                extra_poradi += 10
            elif fmt.kod != kod:
                fmt.kod = kod
                fmt.save(update_fields=["kod"])
            seen_kody.add(kod)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_vyuctovaninastaveni_auto_rezim"),
    ]

    operations = [
        migrations.CreateModel(
            name="CenikFormat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kod", models.CharField(max_length=15, unique=True, verbose_name="Kód")),
                ("nazev", models.CharField(max_length=120, unique=True, verbose_name="Název formátu")),
                ("poradi", models.PositiveSmallIntegerField(default=0, verbose_name="Pořadí")),
            ],
            options={
                "verbose_name": "Formát ceníku",
                "verbose_name_plural": "Formáty ceníku",
                "ordering": ("poradi", "nazev"),
            },
        ),
        migrations.AlterField(
            model_name="cenik",
            name="format",
            field=models.CharField(max_length=15, verbose_name="Formát"),
        ),
        migrations.AlterField(
            model_name="trening",
            name="format",
            field=models.CharField(max_length=15, verbose_name="Formát"),
        ),
        migrations.RunPython(seed_formats, noop),
    ]
