# Generated by Django 5.2.5 on 2026-07-11 21:30

from django.db import migrations, models


VYCHOZI_KODY = {
    "Solo (1 hráč) - Člen": ("SOLO_C", 10),
    "Dvojice (2 hráči) - Člen": ("DVOJICE_C", 20),
    "Trojice (3 hráči) - Člen": ("TROJICE_C", 30),
    "Čtveřice (4 hráči) - Člen": ("CTVRICE_C", 40),
    "Pětice (5 a více hráčů) - Člen": ("PETICE", 50),
    "Solo (1 hráč) - Nečlen": ("SOLO_NC", 60),
    "Dvojice (2 hráči) - Nečlen": ("DVOJICE_NC", 70),
    "Trojice (3 hráči) - Nečlen": ("TROJICE_NC", 80),
    "Čtveřice (4 hráči) - Nečlen": ("CTVRICE_NC", 90),
    "Trénink - Sobota": ("SOBOTA_TRE", 100),
    "Kurt - Rezervace": ("KURT_TRE", 110),
    "Výplet - Standard": ("V_STAND", 120),
    "Výplet - Express": ("V_EXCEL", 130),
    "Výplet - Vlastní": ("V_VLAST", 140),
}

KOD_TO_NAZEV = {kod: nazev for nazev, (kod, _poradi) in VYCHOZI_KODY.items()}


def _table_columns(schema_editor, table):
    with schema_editor.connection.cursor() as cursor:
        return {
            col.name
            for col in schema_editor.connection.introspection.get_table_description(cursor, table)
        }


def ensure_cenikformat_table(apps, schema_editor):
    """Vytvoří tabulku CenikFormat – portable (SQLite i PostgreSQL)."""
    CenikFormat = apps.get_model("core", "CenikFormat")
    table = CenikFormat._meta.db_table
    connection = schema_editor.connection
    tables = connection.introspection.table_names()

    if table not in tables:
        schema_editor.create_model(CenikFormat)
        return

    columns = _table_columns(schema_editor, table)
    if "kod" in columns:
        return

    # Starší lokální schéma bez sloupce kod – přestavět tabulku přes Django ORM.
    with connection.cursor() as cursor:
        cursor.execute(f'SELECT "id", "nazev", "poradi" FROM "{table}"')
        rows = list(cursor.fetchall())

    schema_editor.delete_model(CenikFormat)
    schema_editor.create_model(CenikFormat)

    CenikFormat = apps.get_model("core", "CenikFormat")
    for row_id, nazev, poradi in rows:
        CenikFormat.objects.create(
            id=row_id,
            kod=nazev,
            nazev=nazev,
            poradi=poradi or 0,
        )

    if rows and connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT setval(pg_get_serial_sequence(%s, 'id'), "
                "(SELECT MAX(id) FROM core_cenikformat))",
                [table],
            )


def seed_formats(apps, schema_editor):
    CenikFormat = apps.get_model("core", "CenikFormat")
    Cenik = apps.get_model("core", "Cenik")
    Trening = apps.get_model("core", "Trening")

    seen_kody = set()
    for nazev, (kod, poradi) in VYCHOZI_KODY.items():
        fmt = CenikFormat.objects.filter(nazev=nazev).first()
        if fmt is None:
            fmt = CenikFormat.objects.filter(kod=kod).first()
        if fmt is None:
            CenikFormat.objects.create(kod=kod, nazev=nazev, poradi=poradi)
        else:
            changed = False
            if fmt.kod != kod:
                fmt.kod = kod
                changed = True
            if fmt.nazev != nazev:
                fmt.nazev = nazev
                changed = True
            if fmt.poradi != poradi:
                fmt.poradi = poradi
                changed = True
            if changed:
                fmt.save()
        seen_kody.add(kod)

    extra_poradi = 200
    for model in (Cenik, Trening):
        for kod in model.objects.values_list("format", flat=True).distinct():
            if not kod or kod in seen_kody:
                continue
            nazev = KOD_TO_NAZEV.get(kod, kod)
            fmt = CenikFormat.objects.filter(kod=kod).first()
            if fmt is None:
                fmt = CenikFormat.objects.filter(nazev=nazev).first()
            if fmt is None:
                CenikFormat.objects.create(kod=kod, nazev=nazev, poradi=extra_poradi)
                extra_poradi += 10
            elif fmt.kod != kod:
                fmt.kod = kod
                fmt.save(update_fields=["kod"])
            seen_kody.add(kod)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_vyuctovaninastaveni_auto_rezim"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="CenikFormat",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("kod", models.CharField(max_length=15, unique=True, verbose_name="Kód")),
                        ("nazev", models.CharField(max_length=120, unique=True, verbose_name="Název formátu")),
                        ("poradi", models.PositiveSmallIntegerField(default=0, verbose_name="Pořadí")),
                    ],
                    options={
                        "verbose_name": "Formát ceníku",
                        "verbose_name_plural": "Formáty ceníku",
                        "ordering": ("poradi", "nazev"),
                    },
                ),
                migrations.AlterField(
                    model_name="cenik",
                    name="format",
                    field=models.CharField(max_length=15, verbose_name="Formát"),
                ),
                migrations.AlterField(
                    model_name="trening",
                    name="format",
                    field=models.CharField(max_length=15, verbose_name="Formát"),
                ),
            ],
            database_operations=[
                migrations.RunPython(ensure_cenikformat_table, noop),
            ],
        ),
        migrations.RunPython(seed_formats, noop),
    ]
