# Generated by Django 5.2.5 on 2026-07-12 16:15

from django.db import migrations, models


def rozdelit_jmena(apps, schema_editor):
    """Rozdělí legacy hodnotu z jednoho pole – formát „Příjmení Jméno“ (např. Peterka Jakub)."""
    Hrac = apps.get_model("core", "Hrac")
    for hrac in Hrac.objects.all():
        prijmeni = (hrac.prijmeni or "").strip()
        jmeno = (hrac.jmeno or "").strip()

        # Už rozděleno (oba díly, v jméně není mezera)
        if prijmeni and jmeno and " " not in jmeno:
            continue

        full = jmeno
        if not full and prijmeni:
            full = prijmeni
        if not full:
            hrac.prijmeni = ""
            hrac.jmeno = ""
            hrac.save(update_fields=["jmeno", "prijmeni"])
            continue

        parts = full.split()
        if len(parts) == 1:
            hrac.prijmeni = parts[0]
            hrac.jmeno = ""
        else:
            hrac.prijmeni = parts[0]
            hrac.jmeno = " ".join(parts[1:])
        hrac.save(update_fields=["jmeno", "prijmeni"])


def sloucit_jmena(apps, schema_editor):
    """Zpět do jednoho pole – opět formát „Příjmení Jméno“."""
    Hrac = apps.get_model("core", "Hrac")
    for hrac in Hrac.objects.all():
        prijmeni = (hrac.prijmeni or "").strip()
        jmeno = (hrac.jmeno or "").strip()
        hrac.jmeno = " ".join(p for p in (prijmeni, jmeno) if p)
        hrac.prijmeni = ""
        hrac.save(update_fields=["jmeno", "prijmeni"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_cenikformat"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrac",
            name="prijmeni",
            field=models.CharField(blank=True, db_index=True, default="", max_length=120, verbose_name="Příjmení"),
        ),
        migrations.AlterField(
            model_name="hrac",
            name="jmeno",
            field=models.CharField(max_length=120, verbose_name="Jméno"),
        ),
        migrations.AlterModelOptions(
            name="hrac",
            options={"ordering": ("prijmeni", "jmeno"), "verbose_name": "Hráč", "verbose_name_plural": "Hráči"},
        ),
        migrations.RunPython(rozdelit_jmena, sloucit_jmena),
    ]
