# Generated by Django 5.2.5 on 2026-07-12 16:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_hrac_prijmeni'),
    ]

    operations = [
        migrations.CreateModel(
            name='OstatniNaklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesic', models.DateField(help_text='První den kalendářního měsíce', verbose_name='Měsíc')),
                ('kategorie', models.CharField(choices=[('ENERGIE', 'Energie'), ('BONUSY', 'Bonusy'), ('MIC', 'Míče a protže'), ('VYBAVENI', 'Vybavení'), ('UDRZBA', 'Údržba kurtů'), ('POJISTENI', 'Pojištění'), ('MARKETING', 'Marketing'), ('DOPRAVA', 'Doprava'), ('ADMIN', 'Administrativa'), ('OSTATNI', 'Ostatní')], max_length=20, verbose_name='Kategorie')),
                ('castka', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Částka')),
                ('poznamka', models.CharField(blank=True, default='', max_length=240, verbose_name='Poznámka')),
                ('vytvoreno', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ostatní náklad',
                'verbose_name_plural': 'Ostatní náklady',
                'ordering': ['-mesic', 'kategorie'],
                'indexes': [models.Index(fields=['mesic'], name='core_ostatn_mesic_b0db3a_idx')],
                'constraints': [models.UniqueConstraint(fields=('mesic', 'kategorie'), name='uniq_ostatni_naklad_mesic_kat')],
            },
        ),
    ]
