# Generated by Django 5.2.5 on 2026-07-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_ostatni_naklad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ostatninaklad',
            name='kategorie',
            field=models.CharField(choices=[('ENERGIE', 'Energie'), ('NAJEM', 'Nájem'), ('BONUSY', 'Bonusy'), ('MIC', 'Míče a protže'), ('VYBAVENI', 'Vybavení'), ('UDRZBA', 'Údržba kurtů'), ('POJISTENI', 'Pojištění'), ('MARKETING', 'Marketing'), ('DOPRAVA', 'Doprava'), ('ADMIN', 'Administrativa'), ('OSTATNI', 'Ostatní')], max_length=20, verbose_name='Kategorie'),
        ),
    ]
