# Generated by Django 5.2.5 on 2026-07-13 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_ostatni_naklad_den'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNastaveni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_klubu', models.CharField(default='Tenis systém Čimice', help_text='Zobrazí se v hlavičce a v e-mailech.', max_length=120, verbose_name='Název klubu / systému')),
                ('barevna_varianta', models.CharField(choices=[('oranzova', 'Oranžová'), ('zelena', 'Zelená'), ('modra', 'Modrá'), ('fialova', 'Fialová'), ('cervena', 'Červená')], default='oranzova', help_text='Barevné schéma admin rozhraní.', max_length=16, verbose_name='Barevná varianta')),
            ],
            options={
                'verbose_name': 'Nastavení systému',
                'verbose_name_plural': 'Nastavení systému',
            },
        ),
        migrations.AlterField(
            model_name='transakce',
            name='castka',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Částka'),
        ),
        migrations.AlterField(
            model_name='transakce',
            name='hrac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transakce', to='core.hrac', verbose_name='Hráč'),
        ),
        migrations.AlterField(
            model_name='transakce',
            name='popis',
            field=models.CharField(blank=True, max_length=240, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='transakce',
            name='typ',
            field=models.CharField(choices=[('NAUCTOVANO', 'Naúčtováno'), ('PLATBA', 'Platba'), ('VRATKA', 'Vrácení/bonifikace'), ('UPRAVA', 'Úprava')], max_length=12, verbose_name='Typ'),
        ),
    ]
