# Generated by Django 5.2.5 on 2026-07-13 17:54

from django.db import migrations, models


def seed_system_colors(apps, schema_editor):
    Model = apps.get_model("core", "SystemNastaveni")
    from core.system_theme import MODEL_FIELD_MAP, preset_colors

    for obj in Model.objects.all():
        colors = preset_colors(obj.barevna_varianta or "oranzova", dark=obj.tmavy_rezim)
        for key, field in MODEL_FIELD_MAP.items():
            setattr(obj, field, colors[key])
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_system_nastaveni'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnastaveni',
            name='barva_brand',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Primární akcent'),
        ),
        migrations.AddField(
            model_name='systemnastaveni',
            name='barva_brand_100',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Světlé pozadí akcentu'),
        ),
        migrations.AddField(
            model_name='systemnastaveni',
            name='barva_brand_600',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Akcent tlačítek'),
        ),
        migrations.AddField(
            model_name='systemnastaveni',
            name='barva_ohraniceni',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Ohraničení'),
        ),
        migrations.AddField(
            model_name='systemnastaveni',
            name='barva_plochy',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Karty a formuláře'),
        ),
        migrations.AddField(
            model_name='systemnastaveni',
            name='barva_pozadi',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Pozadí stránky'),
        ),
        migrations.AddField(
            model_name='systemnastaveni',
            name='barva_tabulka_hlava',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Hlavička tabulek'),
        ),
        migrations.AddField(
            model_name='systemnastaveni',
            name='barva_tabulka_hover',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Hover řádku tabulky'),
        ),
        migrations.AddField(
            model_name='systemnastaveni',
            name='barva_tabulka_radek',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Střídavý řádek tabulky'),
        ),
        migrations.AddField(
            model_name='systemnastaveni',
            name='barva_text',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='systemnastaveni',
            name='barva_text_silny',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Tučný text'),
        ),
        migrations.AddField(
            model_name='systemnastaveni',
            name='tmavy_rezim',
            field=models.BooleanField(default=False, help_text='Tmavé pozadí, světlý text a upravené barvy tabulek.', verbose_name='Tmavý režim'),
        ),
        migrations.AlterField(
            model_name='systemnastaveni',
            name='barevna_varianta',
            field=models.CharField(choices=[('oranzova', 'Oranžová'), ('zelena', 'Zelená'), ('modra', 'Modrá'), ('fialova', 'Fialová'), ('cervena', 'Červená')], default='oranzova', help_text='Základní paleta akcentů – jednotlivé barvy lze dále upravit.', max_length=16, verbose_name='Barevná varianta'),
        ),
        migrations.RunPython(seed_system_colors, migrations.RunPython.noop),
    ]
