# Generated by Django 5.2.5 on 2026-07-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_system_nastaveni_vzhled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemnastaveni',
            name='barevna_varianta',
            field=models.CharField(choices=[('oranzova', 'Tenis'), ('modra', 'Modrá'), ('zelena', 'Zelená'), ('cervena', 'Teplá'), ('fialova', 'Fialová'), ('seda', 'Neutrální')], default='oranzova', help_text='Základní paleta akcentů – jednotlivé barvy lze dále upravit.', max_length=16, verbose_name='Barevná varianta'),
        ),
    ]
