# Generated by Django 5.2.5 on 2026-07-14 16:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_system_nastaveni_jazyk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemnastaveni',
            name='barevna_varianta',
            field=models.CharField(choices=[('oranzova', 'Tenis'), ('modra', 'Modrá'), ('zelena', 'Zelená'), ('cervena', 'Teplá'), ('fialova', 'Fialová'), ('seda', 'Neutrální')], default='oranzova', help_text='Paleta barev ve stylu Excel – mění celý vzhled systému.', max_length=16, verbose_name='Barevná varianta'),
        ),
        migrations.AlterField(
            model_name='systemnastaveni',
            name='prah_dluhu_dashboard',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 = všichni se záporným kreditem, −1000 = dluh od 1000 Kč.', max_digits=10, verbose_name='Práh dluhu na dashboardu (Kč)'),
        ),
        migrations.AlterField(
            model_name='systemnastaveni',
            name='slogan',
            field=models.CharField(blank=True, default='', help_text='Krátký text na veřejné stránce.', max_length=160, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='systemnastaveni',
            name='vychozi_delka_minut',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 min'), (45, '45 min'), (60, '1 h'), (90, '1,5 h'), (120, '2 h'), (150, '2,5 h'), (180, '3 h')], default=60, verbose_name='Výchozí délka tréninku'),
        ),
    ]
