# Generated by Django 5.2.5 on 2026-07-16 18:31

import django.utils.timezone
from django.db import migrations, models


def seed_roles_and_preserve_account_labels(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("auth", "User")
    VyuctovaniNastaveni = apps.get_model("core", "VyuctovaniNastaveni")

    platform, _ = Group.objects.get_or_create(name="platform_admin")
    club, _ = Group.objects.get_or_create(name="club_admin")

    for user in User.objects.filter(is_superuser=True):
        user.groups.add(platform, club)
    for user in User.objects.filter(is_staff=True, is_superuser=False):
        user.groups.add(club)

    # Zachovat Čimice labely u existujících účtů (defaulty modelů už jsou generické)
    for nast in VyuctovaniNastaveni.objects.all():
        changed = False
        if nast.ucet_varianta_1 == "2102303853/2700" and nast.ucet_nazev_1 in ("", "Účet 1"):
            nast.ucet_nazev_1 = "Účet 1 AJ Sport"
            changed = True
        if nast.ucet_varianta_2 == "2108539314/2700" and nast.ucet_nazev_2 in ("", "Účet 2"):
            nast.ucet_nazev_2 = "Účet 2 Káťa"
            changed = True
        if changed:
            nast.save()


def unseed_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["platform_admin", "club_admin"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_alter_systemnastaveni_barevna_varianta_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="vyuctovaninastaveni",
            name="ucet_nazev_1",
            field=models.CharField(
                default="Účet 1",
                help_text="Zobrazí se ve výběru varianty e-mailu (např. hlavní účet klubu).",
                max_length=64,
                verbose_name="Název účtu – varianta 1",
            ),
        ),
        migrations.AddField(
            model_name="vyuctovaninastaveni",
            name="ucet_nazev_2",
            field=models.CharField(
                default="Účet 2",
                max_length=64,
                verbose_name="Název účtu – varianta 2",
            ),
        ),
        migrations.AddField(
            model_name="vyuctovaninastaveni",
            name="variabilni_symbol_popis",
            field=models.CharField(
                default="Jméno hráče",
                help_text="Text zobrazený u VS v e-mailu vyúčtování.",
                max_length=120,
                verbose_name="Variabilní symbol (text v e-mailu)",
            ),
        ),
        migrations.AlterField(
            model_name="cenik",
            name="cena_za_hodinu",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Cena za hodinu"
            ),
        ),
        migrations.AlterField(
            model_name="cenik",
            name="kurt",
            field=models.CharField(
                choices=[
                    ("VENEK", "Venku"),
                    ("HALA", "Hala"),
                    ("SLUZBA", "Služba (neplatí pro kurt)"),
                ],
                max_length=8,
                verbose_name="Kurt",
            ),
        ),
        migrations.AlterField(
            model_name="cenik",
            name="platnost_do",
            field=models.DateField(blank=True, null=True, verbose_name="Platnost do"),
        ),
        migrations.AlterField(
            model_name="cenik",
            name="platnost_od",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Platnost od"
            ),
        ),
        migrations.AlterField(
            model_name="systemnastaveni",
            name="email_odesilatel",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Formát: Jméno <email@domena.cz>",
                max_length=120,
                verbose_name="Odesílatel e-mailů",
            ),
        ),
        migrations.AlterField(
            model_name="systemnastaveni",
            name="email_podpis",
            field=models.TextField(
                blank=True,
                default="S pozdravem,\n\nTenisSystém",
                verbose_name="Podpis e-mailů",
            ),
        ),
        migrations.AlterField(
            model_name="systemnastaveni",
            name="email_predmet_prefix",
            field=models.CharField(
                blank=True,
                default="[TenisSystém] ",
                max_length=60,
                verbose_name="Prefix předmětu e-mailu",
            ),
        ),
        migrations.AlterField(
            model_name="systemnastaveni",
            name="nazev_klubu",
            field=models.CharField(
                default="TenisSystém",
                help_text="Zobrazí se v hlavičce a v e-mailech.",
                max_length=120,
                verbose_name="Název klubu / systému",
            ),
        ),
        migrations.AlterField(
            model_name="systemnastaveni",
            name="vychozi_jazyk",
            field=models.CharField(
                choices=[
                    ("cs", "Čeština"),
                    ("en", "English"),
                    ("de", "Deutsch"),
                    ("sk", "Slovenčina"),
                    ("pl", "Polski"),
                    ("es", "Español"),
                    ("fr", "Français"),
                    ("it", "Italiano"),
                    ("nl", "Nederlands"),
                    ("pt", "Português"),
                    ("ru", "Русский"),
                    ("uk", "Українська"),
                ],
                default="cs",
                help_text="Jazyk rozhraní pro celý systém.",
                max_length=10,
                verbose_name="Výchozí jazyk systému",
            ),
        ),
        migrations.AlterField(
            model_name="trening",
            name="kurt",
            field=models.CharField(
                choices=[
                    ("VENEK", "Venku"),
                    ("HALA", "Hala"),
                    ("SLUZBA", "Služba (neplatí pro kurt)"),
                ],
                max_length=8,
                verbose_name="Kurt",
            ),
        ),
        migrations.AlterField(
            model_name="vyuctovaninastaveni",
            name="email_variant",
            field=models.CharField(
                choices=[("1", "Účet 1"), ("2", "Účet 2")],
                default="1",
                max_length=1,
                verbose_name="Výchozí varianta e-mailu",
            ),
        ),
        migrations.AlterField(
            model_name="vyuctovaninastaveni",
            name="ucet_varianta_1",
            field=models.CharField(
                blank=True,
                default="",
                max_length=32,
                verbose_name="Číslo účtu – varianta 1",
            ),
        ),
        migrations.AlterField(
            model_name="vyuctovaninastaveni",
            name="ucet_varianta_2",
            field=models.CharField(
                blank=True,
                default="",
                max_length=32,
                verbose_name="Číslo účtu – varianta 2",
            ),
        ),
        migrations.RunPython(seed_roles_and_preserve_account_labels, unseed_roles),
    ]
