# Generated by Django 5.2.5 on 2026-07-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_saas_prep_roles_and_generic_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodina',
            name='nazev',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Název rodiny (např. Novákovi)'),
        ),
    ]
