# Generated by Django 5.2.5 on 2026-07-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_rodina_generic_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemnastaveni',
            name='logo',
            field=models.ImageField(blank=True, help_text='PNG nebo JPG, čtvercové i kulaté.', null=True, upload_to='club/', verbose_name='Logo klubu'),
        ),
    ]
