# Generated by Django 5.2.5 on 2026-07-27 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_system_logo_help_text_short'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barevna_varianta', models.CharField(blank=True, choices=[('oranzova', 'Tenis'), ('modra', 'Modrá'), ('zelena', 'Zelená'), ('cervena', 'Teplá'), ('fialova', 'Fialová'), ('seda', 'Neutrální')], default='', help_text='Prázdné = výchozí vzhled klubu.', max_length=16, verbose_name='Barevná varianta')),
                ('tmavy_rezim', models.BooleanField(blank=True, help_text='Prázdné = výchozí režim klubu.', null=True, verbose_name='Tmavý režim')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Preference uživatele',
                'verbose_name_plural': 'Preference uživatelů',
            },
        ),
    ]
