# Generated by Django 5.2.5 on 2026-09-11 08:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_systemnastaveni_mena'),
    ]

    operations = [
        migrations.AddField(
            model_name='cenik',
            name='v_kalendari',
            field=models.BooleanField(default=True, help_text='Zobrazit typ tréninku v legendě a barvách rozvrhu.', verbose_name='Přidat do kalendáře'),
        ),
        migrations.AlterField(
            model_name='systemnastaveni',
            name='mena',
            field=models.CharField(choices=[('Evropa', [('CZK', 'Kč – Česká koruna'), ('EUR', '€ – Euro'), ('GBP', '£ – Britská libra'), ('CHF', 'CHF – Švýcarský frank'), ('PLN', 'zł – Polský zlotý'), ('HUF', 'Ft – Maďarský forint'), ('RON', 'lei – Rumunský leu'), ('BGN', 'лв – Bulharský lev'), ('RSD', 'дин – Srbský dinár'), ('UAH', '₴ – Ukrajinská hřivna'), ('TRY', '₺ – Turecká lira'), ('SEK', 'kr – Švédská koruna'), ('NOK', 'kr – Norská koruna'), ('DKK', 'kr – Dánská koruna'), ('ISK', 'kr – Islandská koruna')]), ('Severní Amerika', [('USD', '$ – Americký dolar'), ('CAD', 'C$ – Kanadský dolar'), ('MXN', '$ – Mexické peso')]), ('Jižní Amerika', [('BRL', 'R$ – Brazilský real'), ('ARS', '$ – Argentinské peso'), ('CLP', '$ – Chilské peso'), ('COP', '$ – Kolumbijské peso'), ('PEN', 'S/ – Peruánský sol'), ('UYU', '$U – Uruguayské peso')]), ('Asie', [('JPY', '¥ – Japonský jen'), ('CNY', '¥ – Čínský jüan'), ('KRW', '₩ – Jihokorejský won'), ('INR', '₹ – Indická rupie'), ('IDR', 'Rp – Indonéská rupie'), ('THB', '฿ – Thajský baht'), ('VND', '₫ – Vietnamský dong'), ('MYR', 'RM – Malajsijský ringgit'), ('SGD', 'S$ – Singapurský dolar'), ('HKD', 'HK$ – Hongkongský dolar'), ('TWD', 'NT$ – Tchajwanský dolar'), ('PHP', '₱ – Filipínské peso'), ('AED', 'د.إ – SAE dirham'), ('SAR', '﷼ – Saúdský rijál'), ('ILS', '₪ – Izraelský šekel')])], default='CZK', help_text='Zobrazí se u všech cen a částek v systému (Kč, €, $ …).', max_length=8, verbose_name='Měna'),
        ),
        migrations.AlterField(
            model_name='vyuctovaninastaveni',
            name='auto_castka_k_uhrade',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Částka zobrazená v e-mailu jako požadavek k úhradě. Ponechte 0 pro automatický výpočet z období.', max_digits=10, verbose_name='Částka k zaplacení v e-mailu'),
        ),
        migrations.AlterField(
            model_name='vyuctovaninastaveni',
            name='auto_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Vyúčtování se vytvoří, když kredit hráče klesne na tuto zápornou částku nebo níže (např. −5000).', max_digits=10, verbose_name='Limit kreditu'),
        ),
    ]
